# This configuration file is for experimental use only. Do not use this configuration for training.

# Set random seed to ensure experiment reproducibility
seed: 6

exp_schedule:
  # Number of episodes per experiment configuration
  num_episodes: [20, 20, 20]
  # Number of pursuers per experiment stage
  num_pursuers: [48, 51, 56]
  # Number of evaders per experiment stage
  num_evaders: [12, 13, 14]
  # Number of ocean current fields used per experiment stage
  num_cores: [8, 8, 8]
  # Number of obstacles in the environment per experiment stage
  num_obstacles: [8, 8, 8]
  # Minimum initial distance between pursuers and evaders during experiment
  min_pursuer_evader_init_dis: [20.0, 20.0, 20.0]

# Training parameters
training:
  # Maximum timesteps per episode during training
  episode_max_length: 3000
  update_every: 4

# Environment parameters
env:
  # Width of the environment
  width: 200.0
  # Height of the environment
  height: 200.0
  # Radius around the pursuer that must be free of objects
  clear_r: 15.0
  # Range of obstacle radius
  obs_r_range: [ 1.0, 1.1 ]

  # Sparse reward
  goal_reward: 120.0            # Reward for successful capture

  # Dense rewards
  distance_reward: 5.0          # Reward for getting closer to the target
  timestep_penalty: -1.0        # Penalty per step to encourage faster task completion
  decay_factor: -0.05           # Reward decay factor

  # Penalties
  emergency_penalty: -5.0       # Penalty for emergency situations
  collision_penalty: -80.0      # Penalty for collisions
  boundary_penalty: -5.0        # Penalty for exceeding the boundary

  # Global cooperation reward
  evenly_distributed_reward: 5.0          # Reward for optimal pursuer clustering (3-4 pursuers)
  unevenly_distributed_reward: -10.0      # Penalty for excessive pursuer clustering (>=5 pursuers)

  # Distance thresholds
  capture_distance: 8.0         # Capture distance
  related_distance: 18.0        # Related distance (threshold for determining pursuer-evader interaction)

# Pursuer agent parameters
pursuer:
  # Maximum speed of the pursuer
  max_speed: 3.0
  # Distance within which the pursuer can capture an evader
  distance_capture: env.capture_distance
  # Available acceleration values for the pursuer
  a: [ -0.4, 0.0, 0.4 ]
  # Available angular velocity (turning speed) values for the pursuer
  w: [ -0.5235987755982988, 0.0, 0.5235987755982988 ]
  # Perception range of the pursuer
  perception_range: 20.0

# Evader agent parameters
evader:
  # Maximum speed of the evader
  max_speed: 3.5
  # Available acceleration values for the evader
  a: [ -0.4, 0.0, 0.4 ]
  # Available angular velocity (turning speed) values for the evader
  w: [ -0.5235987755982988, -0.2617993877991494, 0.0, 0.2617993877991494, 0.5235987755982988 ]
  # Perception range of the evader
  perception_range: 20.0

# APF strategy parameters
apf:
  force_range: 15.0

perception:
  # Maximum number of observable evaders
  max_evader_num: 14